version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    branches:
      only:
        - master

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - '9e:c2:a1:a8:38:fc:c3:b5:fb:37:fe:03:28:0b:56:b8'

      - run:
          name: Install pm2
          command: sudo npm install -g pm2

      - run:
          name: deploy
          command: pm2 deploy ecosystem.config.js production
